// Ficha de clientes (importada desde "Ficha de Clientes.xlsx")
// Lista maestra editable. Alimenta el autocompletado al crear facturas/cotizaciones.
export const CLIENTES_FICHA = [
  { id: "cf0", rut: "11.111.111-1", nombre: "CLIENTE GENÉRICO SPyme", giro: "GIRO GENERICO", direccion: "DIRECCION GENERICA", comuna: "las condes", estado: "Activo", vendedor: "" },
  { id: "cf1", rut: "11.207.773-1", nombre: "Roxana Neira", giro: "Fabricación de productos metálicos", direccion: "amino las Higueras parc. 29", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf2", rut: "11.677.971-4", nombre: "Claudia Soto Rojas", giro: "Construcción obras de arte", direccion: "monjitas 738 depto 1406", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf3", rut: "55.555.555-5", nombre: "CLIENTE GENÉRICO 55.", giro: "GIRO GENERICO", direccion: "DIRECCION GENERICA", comuna: "Santiago", estado: "Activo", vendedor: "" },
  { id: "cf4", rut: "59.000.000-0", nombre: "NESTLE SA", giro: "Comercial", direccion: "LA GIACONDA 4326,", comuna: "LAS CONDES", estado: "Activo", vendedor: "VENDEDOR" },
  { id: "cf5", rut: "76.001.610-1", nombre: "JARAS DIESEL LIMITADA", giro: "INDUSTRIAS MANUFACTURERAS METALICAS", direccion: "Alcalde Guzmán 1431,", comuna: "QUILICURA", estado: "Activo", vendedor: "" },
  { id: "cf6", rut: "76.135.769-7", nombre: "COMERCIALIZADORA ROCHY LIMITADA", giro: "Otras actividades de servicios de apoyo a las empresas n.c.p", direccion: "AVENIDA CRISTOBAL COLON 8687", comuna: "Hualpén", estado: "Activo", vendedor: "" },
  { id: "cf7", rut: "76.142.748-2", nombre: "INGECOAT SPA", giro: "Fabricación de otros tipos de maquinaria de uso general", direccion: "Esmeralda 1531", comuna: "Quinta Normal", estado: "Activo", vendedor: "" },
  { id: "cf8", rut: "76.242.181-K", nombre: "KRONOX CHILE SPA", giro: "DEL RUBRO", direccion: "Dir. Gral Holley 2381B, Of 1203", comuna: "PROVIDENCIA", estado: "Activo", vendedor: "" },
  { id: "cf9", rut: "76.255.044-K", nombre: "RENNER COATINGS CHILE SPA", giro: "COMERCIO AL POR MAYOR Y AL POR MENOR", direccion: "Camino a Rinconada 1301", comuna: "PUDAHUEL", estado: "Activo", vendedor: "" },
  { id: "cf10", rut: "76.274.455-4", nombre: "HOWDEN CHILE SPA.", giro: "COMERC, EXP Y SUMINISTRO DE CALENT.DE AIRE Y COMP.PARA LA IN", direccion: "Cordillera 575", comuna: "PUDAHUEL", estado: "Activo", vendedor: "" },
  { id: "cf11", rut: "76.308.342-K", nombre: "maestranza lampa spa", giro: "maestranza", direccion: "HUERFANOS 1147 OF 640 , SANTIAGO, CHACABUCO, XIII REGION METROPOLITANA", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf12", rut: "76.350.724-6", nombre: "INMOBILIARIA Y CONSTRUCTORA GESCO S.A.", giro: "Construcción de edificios para uso residencial", direccion: "AV. DEL VALLE 937 VILLA OF-255", comuna: "Huechuraba", estado: "Activo", vendedor: "" },
  { id: "cf13", rut: "76.368.329-K", nombre: "MAESTRANZA LOS LIBERTADORES LIMITADA", giro: "FABRICACION Y COMERCIALIZACION DE PRODUCTOS METALICOS", direccion: "MANUEL RODRIGUEZ 65 A", comuna: "COLINA", estado: "Activo", vendedor: "" },
  { id: "cf14", rut: "76.457.834-1", nombre: "METALURGICA MACAM SPA", giro: "Venta al por mayor de metales y minerales metalíferos", direccion: "Cal. Autopista Del Sol VILLA S/N Lote A-3 Zona In", comuna: "Peñaflor", estado: "Activo", vendedor: "" },
  { id: "cf15", rut: "76.459.614-5", nombre: "COMPANIA INDUSTRIAL & METALURGICA SPA", giro: "Terminación y acabado de edificios", direccion: "LAS VERONICAS 647", comuna: "Colina", estado: "Activo", vendedor: "" },
  { id: "cf16", rut: "76.466.581-3", nombre: "ACEROS PROCESOS & INGENIERIA SPA", giro: "FABRICACION Y VENTA DE ESTRUCTURAS METAL", direccion: "AVDA. SAN IGNACIO 062-B", comuna: "QUILICURA", estado: "Activo", vendedor: "" },
  { id: "cf17", rut: "76.470.069-4", nombre: "MM ESTRUCTURAS METALICAS LIMITADA", giro: "Terminación y acabado de edificios", direccion: "MINISTRO GANA 613 VILLA MANUEL RODRIGUEZ", comuna: "Lo Prado", estado: "Activo", vendedor: "" },
  { id: "cf18", rut: "76.558.692-5", nombre: "HUGO FERNANDO ESCOBAR ESPINOZA CONTRATISTA EN PINTURAS EIRL", giro: "Terminación y acabado de edificios", direccion: "SANTA ROSA 950 OF. DEPTO A201", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf19", rut: "76.600.766-K", nombre: "INMOBILIARIA E INVERSIONES CONSTRUCAPITAL SP", giro: "construccion", direccion: "Nueva Providencia 1881 of201", comuna: "PROVIDENCIA", estado: "Activo", vendedor: "" },
  { id: "cf20", rut: "76.603.240-0", nombre: "Guillermo Celentano Contenedores Patagonia E.i.r.l", giro: "VENTA AL POR MAYOR DE MAQUINARIA, HERRAMIENTAS, EQUIPO Y MATERIALES N.C.P.. CONTAINERS.", direccion: "General Velzasques 10985", comuna: "SAN BERNARDO", estado: "Activo", vendedor: "" },
  { id: "cf21", rut: "76.665.028-7", nombre: "Asesorías electricidad y electrónica Ltda.", giro: "Reparación de aparatos eléctricos", direccion: "Queltehue Interior 635", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf22", rut: "76.682.722-5", nombre: "SOLUCIONES KAME SPA", giro: "Venta al por menor de computadores equipo periférico program", direccion: "GENERAL DEL CANTO 105 OF. DEPTO 809", comuna: "Providencia", estado: "Activo", vendedor: "" },
  { id: "cf23", rut: "76.702.853-9", nombre: "MAMPARU SPA", giro: "FABRICACION DE PRODUCTOS METALICOS PARA USO ESTRUCTURAL", direccion: "Caletera Ruta 5 Norte, KM 122, Parc.69", comuna: "NOGALES", estado: "Activo", vendedor: "" },
  { id: "cf24", rut: "76.751.381-k", nombre: "Solfa spa", giro: "fabricacion", direccion: "Tarapacá 1113,", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf25", rut: "76.767.952-1", nombre: "GRUPO MISECP SPA", giro: "venta de materiales de construccion", direccion: "URIBE 636 OF 302", comuna: "ANTOFAGASTA", estado: "Activo", vendedor: "" },
  { id: "cf26", rut: "76.783.764-K", nombre: "ECOCLIMA FRIO CALOR SPA", giro: "INSTALACIONES ELECTRICAS.", direccion: "CHAITEN 0708", comuna: "PUERTO MONTT", estado: "Activo", vendedor: "" },
  { id: "cf27", rut: "76.814.696-9", nombre: "INGENIERIA MANUFACTURA Y MONTAJE DE ACEROS SPA", giro: "INDUSTRIA MANUFACTURERA", direccion: "MAIPU", comuna: "MAIPU", estado: "Activo", vendedor: "" },
  { id: "cf28", rut: "76.823.145-1", nombre: "PROASES INGENIERIA SPA", giro: "INGENIERIA", direccion: "quilicura", comuna: "LAS CONDES", estado: "Activo", vendedor: "" },
  { id: "cf29", rut: "76.824.427-8", nombre: "CUMBRES LUMINOSAS SPA", giro: "Construcci?n de carreteras y l?neas de ferrocarril", direccion: "EL QUILLAY 7180 OF. DEPTO CASA VILLA LA ARBOLEDA 1", comuna: "Pe?alol?n", estado: "Activo", vendedor: "" },
  { id: "cf30", rut: "76.832.960-5", nombre: "CONSTRUCTORA TERRATEC LIMITADA", giro: "Construcci?n de edificios para uso residencial", direccion: "PASAJE MONJAS 235", comuna: "Vi?a del Mar", estado: "Activo", vendedor: "" },
  { id: "cf31", rut: "76.860.656-0", nombre: "SERVICIOS REVESTIMIENTOS INDUSTRIALES SPA", giro: "Terminaci?n y acabado de edificios", direccion: "", comuna: "Renca", estado: "Activo", vendedor: "" },
  { id: "cf32", rut: "76.884.327-9", nombre: "SACER SPA", giro: "Terminación y acabado de edificios", direccion: "santiago", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf33", rut: "76.895.798-3", nombre: "METAL?RGICA ATOMET SPA", giro: "Empresas de servicios de ingenier?a y actividades conexas de", direccion: "PARROQUIA 1764", comuna: "San Ram?n", estado: "Activo", vendedor: "" },
  { id: "cf34", rut: "76.899.384-k", nombre: "Vertical Ingeniera SPA", giro: "Ingeniería", direccion: "Av del parue 5993 of 709", comuna: "HUECHURABA", estado: "Activo", vendedor: "" },
  { id: "cf35", rut: "76.957.688-6", nombre: "METALDOOR LIMITADA", giro: "Fabricaci?n de productos met?licos para uso estructural", direccion: "ALTAMIRANO 2466", comuna: "Independencia", estado: "Activo", vendedor: "" },
  { id: "cf36", rut: "76004782-1", nombre: "DEALTEC CHILE SPA", giro: "VENTAS POR MENOR DE PRODUCTOS EN COMERCIO ESPECIALIZADO NCP", direccion: "LARRAIN 6642 OF 215", comuna: "LA REINA", estado: "Activo", vendedor: "" },
  { id: "cf37", rut: "76031005-0", nombre: "INVERSIONES Y ASESORIAS V&M LIMITADA.", giro: "OTRAS ACTIVIDADES DE SERVICIOS PERSONALES N.C.P.", direccion: "NA", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf38", rut: "76126089-8", nombre: "FLEXCO DE CHILE SPA", giro: "Venta al por mayor no especializada", direccion: "AVENIDA JORGE ALESSANDRI 11500,", comuna: "SAN BERNARDO", estado: "Activo", vendedor: "" },
  { id: "cf39", rut: "76185748-7", nombre: "Comercial Grating Metal SpA", giro: "Servicios industriales", direccion: "Av. El Carmen 1397 of 301", comuna: "HUECHURABA", estado: "Activo", vendedor: "" },
  { id: "cf40", rut: "76224051-3", nombre: "VIMAN SPA", giro: "OTRAS ACTIVIDADES EMPRESARIALES", direccion: "Aeropuerto 9390.", comuna: "CERRILLOS", estado: "Activo", vendedor: "" },
  { id: "cf41", rut: "76237450-1", nombre: "Barbato", giro: "Estructuras", direccion: "Santiago", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf42", rut: "76294036-1", nombre: "Equipos y servicios vívelo ltda", giro: "Construcción alquiler de maquinarias y equipos", direccion: "Chillepin salamanca", comuna: "SALAMANCA", estado: "Activo", vendedor: "" },
  { id: "cf43", rut: "76321361-7", nombre: "PDM Industrial y comercial SPA", giro: "INDUSTRIAS MANUFACTURERAS NO METALICAS", direccion: "Av. Progreso 8220", comuna: "LA CISTERNA", estado: "Activo", vendedor: "" },
  { id: "cf44", rut: "76420328-3", nombre: "Serviplas eirl", giro: "Fabricacion de elementos no metalicos", direccion: "Ruta 68 1150", comuna: "VALPARAISO", estado: "Activo", vendedor: "" },
  { id: "cf45", rut: "76476229-0", nombre: "TELECOMUNICACION Y ENERGIA ACCECOM SPA", giro: "OBRAS INGENIERIA", direccion: "PASAJE ALQUIMIA N2966", comuna: "MAIPU", estado: "Activo", vendedor: "" },
  { id: "cf46", rut: "76497258-9", nombre: "Earth Archaeological Consultan y Estudios Patrimoniales", giro: "Arqueología", direccion: "Parcela 21", comuna: "PAIHUANO", estado: "Activo", vendedor: "" },
  { id: "cf47", rut: "76500458-6", nombre: "ESIGSA LTDA", giro: "servicios de ingeneria.", direccion: "Dirección los olivos 1255", comuna: "PUDAHUEL", estado: "Activo", vendedor: "" },
  { id: "cf48", rut: "76659281-3", nombre: "PREUNIVERSITARIO TUTOR U CHILE SPA", giro: "Educacion", direccion: "FRANCISCO BILBAO 2945", comuna: "PROVIDENCIA", estado: "Activo", vendedor: "" },
  { id: "cf49", rut: "76814696-9", nombre: "INGENIERIA MANUFACTURA Y MONTAJE DE ACEROS SPA", giro: "ING. FABRICACION, REVESTIMIENTO YY MONTAJE DE PRODUCTOS DE ACERO", direccion: "CHAÑARCILLO 1141", comuna: "MAIPU", estado: "Activo", vendedor: "" },
  { id: "cf50", rut: "76866514-1", nombre: "INGENIUS GESTION DE PROYECTOS SP", giro: "CONSTRUCCI", direccion: "SANTA GRACIELA PARCELA 10", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf51", rut: "76910737-1", nombre: "CONSTRUCCIONES METALSE SPA", giro: "construcci", direccion: "CAMINO INTERIOR 1439 A, LAMPA, CHACABUCO,", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf52", rut: "76959111-7", nombre: "SERVICIO DE REVESTIMIENTOS EN CAUCHO SPA", giro: "SERVICIO DE REVESTIMIENTOS EN CAUCHO SPA", direccion: "BRUNO CASANOVA 2334", comuna: "SAN BERNARDO", estado: "Activo", vendedor: "" },
  { id: "cf53", rut: "76971835-4", nombre: "CADM SPA", giro: "INGENIERIA", direccion: "BAQUEDANO 239", comuna: "ANTOFAGASTA", estado: "Activo", vendedor: "" },
  { id: "cf54", rut: "76971992-k", nombre: "CONSTRUCAPITAL SPA", giro: "CONSTRUCCION", direccion: "MAQUHUE SUR 520 DPTO 205", comuna: "LAS CONDES", estado: "Activo", vendedor: "" },
  { id: "cf55", rut: "77.026.036-1", nombre: "IQ INGENIERIA SPA", giro: "", direccion: "", comuna: "", estado: "Activo", vendedor: "" },
  { id: "cf56", rut: "77.071.286-6", nombre: "Maestranza Union Cepol SPA.", giro: "maestranza", direccion: "Uno Sur 135, Huertos Familiares,", comuna: "TIL TIL", estado: "Activo", vendedor: "" },
  { id: "cf57", rut: "77.079.343-2", nombre: "MAESTRANZA L&T SPA", giro: "Sin información", direccion: "SANTIAGO", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf58", rut: "77.156.319-8", nombre: "FS CHILE 4 SPA", giro: "-", direccion: "Av. Apoquindo 6418", comuna: "Las Condes", estado: "Activo", vendedor: "" },
  { id: "cf59", rut: "77.235.461-4", nombre: "INMOBILIARIA LAS DALIAS SPA", giro: "inmobiliaria", direccion: "AGUSTINAS 853 OF 523", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf60", rut: "77.261.280-K", nombre: "FALABELLA RETAIL S.A.", giro: "Comercial", direccion: "MANUEL RODRIGUEZ NORTE 730,", comuna: "SANTIAGO", estado: "Activo", vendedor: "VENDEDOR" },
  { id: "cf61", rut: "77.265.170-8", nombre: "ARQUIDECO SERVICE LIMITADA", giro: "Terminaci?n y acabado de edificios", direccion: "LAS ARAUCARIAS 8520", comuna: "La Florida", estado: "Activo", vendedor: "" },
  { id: "cf62", rut: "77.270.152-7", nombre: "BENDMETAL FABRICACION Y SERVICIOS SPA", giro: "INDUSTRIAS MANUFACTURERAS METALICAS", direccion: "Cañaveral 1070 Galpón No. 3 Quilicura", comuna: "QUILICURA", estado: "Activo", vendedor: "" },
  { id: "cf63", rut: "77.299.090-1", nombre: "MACIN LTDA", giro: "FORJA, PRENSADO, ESTAMPADO Y LAMINADO DE METALES, PULVIMETALURGIA", direccion: "SANTA MARGARITA 0190 DPTO. LOCAL", comuna: "CONCHALI", estado: "Activo", vendedor: "" },
  { id: "cf64", rut: "77.322.916-3", nombre: "SEMIND SPA", giro: "", direccion: "", comuna: "", estado: "Activo", vendedor: "" },
  { id: "cf65", rut: "77.474.332-4", nombre: "Hecovil Spa", giro: "Metal mecánica", direccion: "agua santa 1622", comuna: "santiago", estado: "Activo", vendedor: "" },
  { id: "cf66", rut: "77.510.000-1", nombre: "MAESTRANZA, CONSTRUCCION Y SERVICIOS A LA MINERIA FARIAS LTDA.", giro: "MAESTRANZA, SOLDADURA, SERVICIOS Y VENTA DE INSUMOS A LA MINERIA", direccion: "AV. LAS INDUSTRIAS ST.11", comuna: "CALAMA", estado: "Activo", vendedor: "" },
  { id: "cf67", rut: "77.571.810-2", nombre: "ZIEBTEC", giro: "MINERIA", direccion: "CHOPIN 2922", comuna: "SAN JOAQUIN", estado: "Activo", vendedor: "" },
  { id: "cf68", rut: "77.605.400-3", nombre: "Cofama S.A", giro: "VENTA AL POR MAYOR NO ESPECIALIZADA", direccion: "José Ananías 207", comuna: "MACUL", estado: "Activo", vendedor: "" },
  { id: "cf69", rut: "77.652.381-K", nombre: "IQ INGENIERIA & MAESTRANZA SPA", giro: "", direccion: "", comuna: "", estado: "Activo", vendedor: "" },
  { id: "cf70", rut: "77.683.790-3", nombre: "FAM América Latina Maquinarias Limitada", giro: "Servicios de Ingeniería", direccion: "Alcántara 200", comuna: "LAS CONDES", estado: "Activo", vendedor: "" },
  { id: "cf71", rut: "77.729.613-2", nombre: "A&B PROYECTOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo", vendedor: "" },
  { id: "cf72", rut: "77.773.740-6", nombre: "INGENIERIA Y SERVICIOS INDUSTRIALES T&T LIMITADA", giro: "Fabricaci?n de otros productos elaborados de metal n.c.p.", direccion: "JAVIERA CARRERA 114 VILLA LOS LIBERTADORES", comuna: "Colina", estado: "Activo", vendedor: "" },
  { id: "cf73", rut: "77.777.777-7", nombre: "COMERCIAL HQ GROUP", giro: "-", direccion: "-", comuna: "-", estado: "Activo", vendedor: "" },
  { id: "cf74", rut: "77.815.304-1", nombre: "LOS METAL SPA", giro: "Sin información", direccion: "", comuna: "Sin información", estado: "Activo", vendedor: "" },
  { id: "cf75", rut: "77.836.230-9", nombre: "SOC COMERCIAL SOCOVAL LIMITADA", giro: "Construcci?n de carreteras y l?neas de ferrocarril", direccion: "PC. SANTA AMALIA VILLA 6B 17B Y 6B 18B", comuna: "Quillota", estado: "Activo", vendedor: "" },
  { id: "cf76", rut: "77.861.306-9", nombre: "SERVICIOS INTEGRALES SEMIND SPA", giro: "", direccion: "", comuna: "", estado: "Activo", vendedor: "" },
  { id: "cf77", rut: "77004851-6", nombre: "SOCIEDAD VETERINARIA HVM SPA", giro: "VETERINARIA", direccion: "CUATRO PONIENTE 1714", comuna: "MAIPU", estado: "Activo", vendedor: "" },
  { id: "cf78", rut: "77035202-9", nombre: "servicios de ingeniería y construcción hammer spa", giro: "construccion", direccion: "pasaje 449 1684", comuna: "PEÑALOLEN", estado: "Activo", vendedor: "" },
  { id: "cf79", rut: "77095321-9", nombre: "Construcciones Sergio Cabrapan EIRL", giro: "construcciones y revestimientos", direccion: "pasaje araucania 699", comuna: "EL BOSQUE", estado: "Activo", vendedor: "" },
  { id: "cf80", rut: "77117739-5", nombre: "Antumetal SPA", giro: "Fabricaci", direccion: "Faro evangelista 211", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf81", rut: "77340593-K", nombre: "PROYECTOS LASER CYG SPA", giro: "fabricacion de estructuras metalicas", direccion: "CAM MELIPILLA 1630", comuna: "PADRE HURTADO", estado: "Activo", vendedor: "" },
  { id: "cf82", rut: "77431750-3", nombre: "MAESTRANZA OVIEDO Y CIA LTDA", giro: "FABRICACI", direccion: "Calle Vista Hermosa 9630", comuna: "CERRILLOS", estado: "Activo", vendedor: "" },
  { id: "cf83", rut: "77474332-4", nombre: "ECOVIL SPA", giro: "FABRICACION DE INSUMOS MINEROS", direccion: "RUTA 5 NORTE 19434", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf84", rut: "77569492-0", nombre: "SANEXP SERVICIOS INDUSTRIALES SPA", giro: "SERVICIOS APOYO EMPRESA", direccion: "AVENIDA PACIFICO 2800 OF217", comuna: "LA SERENA", estado: "Activo", vendedor: "" },
  { id: "cf85", rut: "77586260-2", nombre: "INGENIERIA Y PROYECTOS INGEMIN LTDA", giro: "INGENIERIA MINERA", direccion: "Moneda 1040 Of. 1206 Piso 12", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf86", rut: "77594277-0", nombre: "STEEL PARTNERS", giro: "fabricaci", direccion: "Caletera Autopista del Sol", comuna: "PEÑAFLOR", estado: "Activo", vendedor: "" },
  { id: "cf87", rut: "77681240-4", nombre: "Soc. Comercial Fonseca e Hijos Ltda", giro: "Comercio al por mayor", direccion: "Radal 1737", comuna: "QUINTA NORMAL", estado: "Activo", vendedor: "" },
  { id: "cf88", rut: "77710562-0", nombre: "INNOVATEC INGENIERIA Y DESORROLLO SPA", giro: "SEV INGENIERIA", direccion: "AGUSTINAS 1022 1001", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf89", rut: "77737642-K", nombre: "HYDRO QUIALITY SPA", giro: "TRATAMIENTO DE AGUAS", direccion: "CARLOS TORIBIO RABINET 1315", comuna: "INDEPENDENCIA", estado: "Activo", vendedor: "" },
  { id: "cf90", rut: "77777777-4", nombre: "RM ING", giro: "RM ING", direccion: "RM ING", comuna: "ALHUE", estado: "Activo", vendedor: "" },
  { id: "cf91", rut: "77879620-1", nombre: "MOLDAJES ALSINA LTDA", giro: "MOLDAJES", direccion: "NUEVA TRAQUERAL 612", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf92", rut: "77954088-K", nombre: "PRODUCCION Y SERVICIOS TEMSA SPA", giro: "SERVICIOS DE INGENIERIA", direccion: "vCAM INTERIOR ST 32 A FDO STA ISABEL- LAMPA", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf93", rut: "78.079.141-1", nombre: "Constructora Tesla Spa", giro: "terminaciones y Acabado de edificios", direccion: "Manuel Rodriguez 3650", comuna: "RECOLETA", estado: "Activo", vendedor: "" },
  { id: "cf94", rut: "78.111.866-4", nombre: "MYG SERVICIO INDUSTRIALES SPA", giro: "FABRICACION Y REPARACION DE EQUIPOS PARA LA MINERIA", direccion: "PANAMERICANA NORTE KM 108,", comuna: "HIJUELAS", estado: "Activo", vendedor: "" },
  { id: "cf95", rut: "78.325.590-1", nombre: "TRANSPORTES EQUIPOS Y MAQUINARIAS TREYMAQ Y CIA LTDA", giro: "Construcci?n de edificios para uso residencial", direccion: "", comuna: "San Ram?n", estado: "Activo", vendedor: "" },
  { id: "cf96", rut: "78.951.060-1", nombre: "MAESTRANZA ISTRIA Y COMPANIA LIMITADA", giro: "Venta al por mayor de maquinaria metalurgica para la mineria", direccion: "SAN VICENTE 1346", comuna: "Santiago", estado: "Activo", vendedor: "" },
  { id: "cf97", rut: "78061588-5", nombre: "IMPRESIONES TESLA SPA", giro: "impresiones", direccion: "M RODRIGUEZ 3650 RECOLETA", comuna: "RECOLETA", estado: "Activo", vendedor: "" },
  { id: "cf98", rut: "78314937-0", nombre: "RM INGENIERIA", giro: "OBRAS MAYORES", direccion: "CERRO EL PLOMO 5931, LAS CONDES", comuna: "LAS CONDES", estado: "Activo", vendedor: "" },
  { id: "cf99", rut: "78731960-2", nombre: "MONTAJES INDUSTRIALES CAINOX LTDA", giro: "ABEDULES 677", direccion: "MONTAJES INDUSTRIALES", comuna: "PEÑAFLOR", estado: "Activo", vendedor: "" },
  { id: "cf100", rut: "8099175-4", nombre: "MILTON ASTUDILLO CAPETILLO", giro: "SERVICIOS A LA MINERIA Y CONSTRUCCION", direccion: "PEDRO AGUIRRE CERDA 6097", comuna: "ANTOFAGASTA", estado: "Activo", vendedor: "" },
  { id: "cf101", rut: "89.026.600-2", nombre: "Tecnologia En Transporte De Minerales S.a.", giro: "CORREAS TRANSPORTADORAS.", direccion: "Av. El Arrayán 1306", comuna: "PUDAHUEL", estado: "Activo", vendedor: "" },
  { id: "cf102", rut: "89.895.100-6", nombre: "TECNOLOGIA EN PROCESAMIENTOS DE MINERALES S.A.", giro: "Venta al por mayor no especializada", direccion: "VATICANO 4097", comuna: "LAS CONDES", estado: "Activo", vendedor: "" },
  { id: "cf103", rut: "89201400-0", nombre: "ENVASES IMPRESOS CORDILLERA SPA", giro: "papelera", direccion: "Panamericana Norte 300, huertos familiares", comuna: "TIL TIL", estado: "Activo", vendedor: "" },
  { id: "cf104", rut: "89895100-6", nombre: "TECNOLOGIA EN PROCESAMIENTOS DE MINERALES S.A.", giro: "Suministros para la Minería", direccion: "Calle Vaticano 4097", comuna: "LAS CONDES", estado: "Activo", vendedor: "" },
  { id: "cf105", rut: "90222000- 3", nombre: "EMPRESAS CMPC S.A.", giro: "Papelera", direccion: "AGUSTINAS 1343 PISO 3", comuna: "SANTIAGO", estado: "Activo", vendedor: "" },
  { id: "cf106", rut: "91.947.000-3", nombre: "SIKA S A CHILE", giro: "Venta al por mayor de productos qu?micos", direccion: "QUILICURA", comuna: "San Joaqu?n", estado: "Activo", vendedor: "" },
  { id: "cf107", rut: "91619000-K", nombre: "VULCO S A", giro: "venta productos mineria", direccion: "SAN JOSE 0815", comuna: "SAN BERNARDO", estado: "Activo", vendedor: "" },
  { id: "cf108", rut: "92.617.000-7", nombre: "INGOMAR S A", giro: "Fabricación de otros productos de caucho", direccion: "ALSINO 5473", comuna: "QUINTA NORMAL", estado: "Activo", vendedor: "" },
  { id: "cf109", rut: "93.402.000-6", nombre: "REVESOL S. A.", giro: "Fabricaci?n de partes piezas y accesorios para veh?culos aut", direccion: "CAMINO MIRAFLORES 9553", comuna: "Pudahuel", estado: "Activo", vendedor: "" },
  { id: "cf110", rut: "96.716.200-0", nombre: "Inversiones E Inmobiliaria El Rosal S.a.", giro: "Sociedad de Inversiones y Arriendo de Bienes Inmuebles.", direccion: "Av. Américo Vespucio 1155", comuna: "HUECHURABA", estado: "Activo", vendedor: "" },
  { id: "cf111", rut: "96.853.940-K", nombre: "PROMET SERVICIOS SPA", giro: "Construcci?n de edificios para uso residencial", direccion: "AV DEL VALLE SUR 650 BLOQUE OF 31", comuna: "Huechuraba", estado: "Activo", vendedor: "" },
  { id: "cf112", rut: "96.874.050-4", nombre: "TECNOLOGIA Y SISTEMAS EN ACERO S A", giro: "Fabricaci?n de colchones fabricaci?n de otros muebles n.c.p.", direccion: "DG JOSE M CARO 2630", comuna: "Recoleta", estado: "Activo", vendedor: "" },
  { id: "cf113", rut: "96876460-8", nombre: "Foraction Chili S.A.", giro: "ASERRADERO", direccion: "Curanilahue, Bío Bío", comuna: "CURANILAHUE", estado: "Activo", vendedor: "" },
  { id: "cf114", rut: "96924780-1", nombre: "Reliper LTDA", giro: "INSUMOS MINEROS", direccion: "Camino Lo Boza 386", comuna: "QUILICURA", estado: "Activo", vendedor: "" },
  { id: "cf115", rut: "96945210-3", nombre: "ECO RILES SPA", giro: "Tratamiento de Residuos Industriales", direccion: "WALTER LIHN 1868", comuna: "INDEPENDENCIA", estado: "Activo", vendedor: "" },
  { id: "cf116", rut: "99.528.050-7", nombre: "WEG CHILE SPA", giro: "COMERCIO AL POR MAYOR Y AL POR MENOR", direccion: "Calle Salar De Llamara 808-810", comuna: "PUDAHUEL", estado: "Activo", vendedor: "" },
  { id: "cf117", rut: "99537280-0", nombre: "TECNOACERO S A", giro: "SERVICIOS DE INGENIERIA PRESTADOS POR EMPRESAS N.C.P", direccion: "CAMINO SANTA MARTA 1600", comuna: "MAIPU", estado: "Activo", vendedor: "" },
  { id: "cf118", rut: "KRO.NOS. MI.NIN-G", nombre: "KRONOS MINING ING Y REVESTIMIENTOS LTDA", giro: "FABRIACI", direccion: "PANAMERICANA NORTE 22650 B4", comuna: "LAMPA", estado: "Activo", vendedor: "" },
  { id: "cf119", rut: "VI.CHE-R", nombre: "VICHER SPA", giro: "CONSTRUCCION", direccion: "AV LEON BUSTOS", comuna: "COLBUN", estado: "Activo", vendedor: "" },
]
