// Ficha de proveedores (importada desde "Ficha de Proveedores.xlsx")
// Lista maestra editable de proveedores.
export const PROVEEDORES_FICHA = [
  { id: "pf0", rut: "10.726.005-6", nombre: "LUIS ARTURO QUINONES TOBAR", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf1", rut: "10220193-0", nombre: "ROBERTO ANTONIO MAULEN CONCHA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf2", rut: "11.111.111-1", nombre: "CLIENTE GENÉRICO SPyme", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf3", rut: "11.486.764-0", nombre: "OLGA DEL PILAR GONZALEZ MARQUEZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf4", rut: "12.262.374-2", nombre: "MARCELO JAVIER VEAS CABRERA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf5", rut: "12.294.263-5", nombre: "SERGIO BENITO GONZALEZ CASTRO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf6", rut: "12.405.682-9", nombre: "MANUEL PATRICIO SOZA CEBALLOS", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf7", rut: "12.478.938-9", nombre: "CLAUDIAANDREAKINGBOBADILLA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf8", rut: "12.481.585-1", nombre: "MIGUEL ONOFRE CASTRO AGUILA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf9", rut: "12.642.577-5", nombre: "ROXANA ANDREA CASTRO GUTIERREZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf10", rut: "12.705.312-K", nombre: "JUAN BERNARDINO MEYER RECABAL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf11", rut: "12.740.076-8", nombre: "EDUARDOROSENDORAILAFBULNES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf12", rut: "12.811.972-8", nombre: "JULIOANDRESYANEZCARRILLO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf13", rut: "12.958.610-9", nombre: "JAIME ERNESTO OLIVA MENDEZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf14", rut: "12877112-3", nombre: "YAZMIN ANDREA CHOCAIR PARRA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf15", rut: "13.070.112-4", nombre: "HIPOLITO ULISES ACEVEDO FUENTES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf16", rut: "13065428-2", nombre: "XXXXXX", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf17", rut: "13919617-1", nombre: "EDUARDO DANILO PURRAN MELIMAPO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf18", rut: "14.163.551-4", nombre: "LUIS GONZALO TOBAR GAJARDO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf19", rut: "14.323.288-3", nombre: "CLAUDIO ARMANDO URIBE CASTRO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf20", rut: "14.342.278-K", nombre: "SUSANA DEL CARMEN PALMA GONZALEZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf21", rut: "14.475.199-K", nombre: "MARCOANTONIOGALLEGOSSALAZAR", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf22", rut: "14.500.867-0", nombre: "DOMINGO ESTEBAN ACEITUNO PACHECO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf23", rut: "14.645.457-7", nombre: "HUA HE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf24", rut: "14.903.941-4", nombre: "PAUL ANDRES MONTALVA CIFUENTES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf25", rut: "15.588.213-1", nombre: "MARIELA DE LOURDES VALENZUELA ZUNIGA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf26", rut: "15.898.775-9", nombre: "LUIS ALEJANDRO HERRERA MOLINA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf27", rut: "77.314.397-8", nombre: "CONSTRUCTOR31SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf28", rut: "77.864.520-3", nombre: "AUTHIEVRE MOTORS CENTER SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf29", rut: "77.865.854-2", nombre: "SOCIEDAD COMERCIALIZADORA 2R SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf30", rut: "77.887.104-1", nombre: "ECFAL SERVICIOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf31", rut: "77.915.570-6", nombre: "COMERCIAL MC FERRO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf32", rut: "77.916.175-7", nombre: "El Container SpA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf33", rut: "77.920.095-7", nombre: "COMERCIAL TIGRE DORADO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf34", rut: "77.311.089-1", nombre: "BRABOMBAS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf35", rut: "77.926.998-1", nombre: "ECOMINETECHNOLOGIESSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf36", rut: "77.931.120-1", nombre: "HOMS PACK SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf37", rut: "77.943.157-6", nombre: "Morelav Digital Group SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf38", rut: "77.944.005-2", nombre: "ESTAMPADOS TEXTILES TUPONELMONO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf39", rut: "77.949.283-4", nombre: "Codipal Spa", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf40", rut: "77.978.895-4", nombre: "CAVA LA MONTAÑA CHICUREO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf41", rut: "77.980.500-K", nombre: "CENTRO DE ERGONOMIA Y SALUD OCUPACIONAL CESO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf42", rut: "77.307.127-6", nombre: "FERRETERIA ABADTC SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf43", rut: "77.305.205-0", nombre: "SOCIEDAD COMERCIAL FULL GASES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf44", rut: "77.302.440-5", nombre: "TECNORED S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf45", rut: "78.023.550-0", nombre: "CASA ROSSIER LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf46", rut: "78.059.053-K", nombre: "SERVICIODEMANTENIMIENTOINDUSTRIALCRISTOPHERFELIPEGONZÁLEZGONZÁL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf47", rut: "77.297.926-6", nombre: "SERVIFERCHILE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf48", rut: "77.295.389-5", nombre: "COMERCIAL VRS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf49", rut: "77.292.257-4", nombre: "COMERCIAL BESHTE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf50", rut: "77.288.842-2", nombre: "METAL MECÁNICA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf51", rut: "77.285.385-8", nombre: "INVERSIONES SAN MARTIN SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf52", rut: "78.132.370-5", nombre: "SOC FLORENTINO GARCIA Y CIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf53", rut: "78.138.206-K", nombre: "SERVICIOS KAPLEN SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf54", rut: "78.140.507-8", nombre: "ABARSALMONTAJESSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf55", rut: "77.283.089-0", nombre: "SERVICIOAUTOMOTRIZMEDICAR'SSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf56", rut: "77.280.217-K", nombre: "BARRACADEMADERACLODOMIROHUMBERTOALCAINOOYARZUNE.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf57", rut: "78.227.024-9", nombre: "CONTAINERFULLSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf58", rut: "78.280.912-1", nombre: "JJJ SERVICIO DE TRANSPORTE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf59", rut: "78.284.080-0", nombre: "NEGRETE Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf60", rut: "78.314.360-7", nombre: "REVESTIMIENTOS RUBIO S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf61", rut: "78.323.060-7", nombre: "ASISTENCIA POST VENTA SOCIEDAD ANONIMA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf62", rut: "78.352.311-6", nombre: "INGESAFE EXPERTOS EN SEGURIDAD Y GESTIÓN PREVENTIVA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf63", rut: "78.526.430-4", nombre: "REPRESENTACIONES CANONTEX LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf64", rut: "77.263.664-4", nombre: "FRANCISCO GABRIEL BRITO HUENUPI E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf65", rut: "78.624.290-8", nombre: "EQUIPOS DE IZAJE PROWINCH CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf66", rut: "78.627.210-6", nombre: "HIPERMERCADOS TOTTUS SA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf67", rut: "78.643.000-3", nombre: "INGENIERIA Y SERVICIOS DE IQUIQUE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf68", rut: "78.701.740-1", nombre: "WURTH CHILE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf69", rut: "78.713.970-1", nombre: "INDUSTRIA METALMECANICA UPMETAL CHILE LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf70", rut: "78.741.950-K", nombre: "ZOILO RAMIREZ MOLINA Y CIA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf71", rut: "78.745.710-K", nombre: "ALVARADO HERMANOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf72", rut: "78.856.680-8", nombre: "SM CYCLO COMERCIALIZADORA DE MAQUINARIAS LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf73", rut: "78.885.550-8", nombre: "PERSONAL COMPUTER FACTORY SOCIEDAD ANONIMA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf74", rut: "78.924.030-2", nombre: "IMPLEMENTOS S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf75", rut: "78.936.330-7", nombre: "INNOVACION Y TECNOLOGIA EMPRESARIAL ITEM LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf76", rut: "78.951.060-1", nombre: "MAESTRANZA ISTRIA Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf77", rut: "78.984.330-9", nombre: "SOC COMERCIAL RUBIO Y RUBIO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf78", rut: "79.501.190-0", nombre: "ING SALUD ISAPRE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf79", rut: "77.262.400-K", nombre: "COMERCIAL OXIMARKET LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf80", rut: "77.262.330-5", nombre: "COMERCIAL STYLE GLASS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf81", rut: "79.906.120-1", nombre: "ISAPRE CRUZ DEL NORTE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf82", rut: "79.992.390-4", nombre: "RUBEN SFEIR E HIJOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf83", rut: "79996420-1", nombre: "MARSELLA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf84", rut: "8.409.664-4", nombre: "MARCOS SIMON ZAMBON BERLAGOSKY", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf85", rut: "8.533.962-1", nombre: "ANTONIO PEREZ PEREZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf86", rut: "8.717.401-8", nombre: "PATRICIO RAMON HERRERA SOLER", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf87", rut: "8.860.579-9", nombre: "JUAN ALEJANDRO JAQUE FERNANDEZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf88", rut: "77.261.280-K", nombre: "FALABELLA RETAIL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf89", rut: "77.258.914-K", nombre: "COMERCIAL Y TRANSPORTE CHURA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf90", rut: "77.242.911-8", nombre: "DPAIRLESS CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf91", rut: "81.198.400-0", nombre: "AUTOMOTORA INALCO S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf92", rut: "81.201.000-K", nombre: "CENCOSUD RETAIL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf93", rut: "81.286.300-2", nombre: "CIA TRATAMIENTOS DE AGUA Y COMBUSTION LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf94", rut: "81.293.200-4", nombre: "AUSIN HNOS S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf95", rut: "81.440.500-1", nombre: "ACO MAQUINARIAS SA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf96", rut: "77.241.781-0", nombre: "WLADIMIR CORTES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf97", rut: "77.235.622-6", nombre: "IMPORTADORA Y COMERCIALIZADORA BRAVO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf98", rut: "81.826.800-9", nombre: "CCAF LOS ANDES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf99", rut: "82.525.800-0", nombre: "VETO Y CIA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf100", rut: "82.606.800-0", nombre: "CCAF 18 DE SEPTIEMBRE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf101", rut: "82.698.300-0", nombre: "FERRETERIA ENOL LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf102", rut: "82.925.600-2", nombre: "LAZOS Y CIA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf103", rut: "83.030.600-5", nombre: "ELECTRONICA CASA ROYAL LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf104", rut: "83.176.400-7", nombre: "FERRETERIA CAUPOLICAN S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf105", rut: "83.547.100-4", nombre: "AUTORENTAS DEL PACIFICO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf106", rut: "77.232.430-8", nombre: "PINTURAS INDUSTRIALES GARBAR SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf107", rut: "84.107.900-0", nombre: "PATRICIO BAR Y CIA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf108", rut: "84.249.300-5", nombre: "Quimica Universal Ltda.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf109", rut: "84.634.200-1", nombre: "QUIMICA PASSOL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf110", rut: "85.207.100-1", nombre: "SOCIEDAD DE DIFUSION DE MUSICA AMBIENTAL SCAMUSICA S.A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf111", rut: "85.896.100-9", nombre: "SERVICIOS EQUIFAX CHILE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf112", rut: "85.986.000-1", nombre: "COMPLEMENTOS SANITARIOS CHILE LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf113", rut: "86.063.300-0", nombre: "MUSALEM BENDEK MAQUINARIAS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf114", rut: "86.211.800-6", nombre: "FERROBAL LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf115", rut: "77.229.614-2", nombre: "COMERCIALIZADORA SALAZAR LOYOLA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf116", rut: "87.605.600-3", nombre: "PINTURAS HEMPEL CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf117", rut: "88.293.600-7", nombre: "COMERCIALIZADORA,DISTRIBUIDORA E INDUSTRIAL CODINSA LIMITADA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf118", rut: "88.855.300-2", nombre: "OTERO Y DOMINGUEZ LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf119", rut: "89.005.900-7", nombre: "COMERCIAL ANTUCO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf120", rut: "89.203.200-9", nombre: "DESIDERIO APABLAZA E HIJO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf121", rut: "89.371.100-7", nombre: "REPETTO Y GAJARDO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf122", rut: "89.396.900-4", nombre: "DISTRIBUIDORA TECNICA ELECTRICA VITEL S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf123", rut: "77.217.733-K", nombre: "GONZALEZ HERMANOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf124", rut: "77.208.673-3", nombre: "FERRETERIA DEL SOLDADOR FELIPE VILLASECA E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf125", rut: "77.205.811-K", nombre: "FERRADA PULIDO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf126", rut: "89.862.200-2", nombre: "LATAM AIRLINES GROUP S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf127", rut: "89.910.400-5", nombre: "CORREDORES DE PROPIEDADES URBAC LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf128", rut: "8930416-4", nombre: "RAFAEL PATRICIO PINOHET CAVIERES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf129", rut: "77.203.783-K", nombre: "COMERCIAL FAUNA SALUD SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf130", rut: "77.201.980-7", nombre: "ASTRA IMPORTADORA Y EXPORTADORA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf131", rut: "77.200.531-8", nombre: "INVERSIONES RJCP SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf132", rut: "9.672.522-1", nombre: "ERIKADELPILARDIAZBARRERA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf133", rut: "9.775.555-8", nombre: "CARLOS JOHNNY CABEZAS ROMERO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf134", rut: "91.947.000-3", nombre: "SIKA S A CHILE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf135", rut: "92.065.000-7", nombre: "INDUSTRIA METALURGICA URSUS TROTTER S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf136", rut: "77.188.911-5", nombre: "KOTA 0 CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf137", rut: "77.186.746-4", nombre: "INDUSTRIAS CP SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf138", rut: "93.129.000-2", nombre: "COLCHONES ROSEN SAIC", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf139", rut: "93.305.000-9", nombre: "PROVEEDORA INDUSTRIAL MINERA ANDINA S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf140", rut: "93.447.000-1", nombre: "QUIMICA DEL CAMPO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf141", rut: "93.772.000-9", nombre: "PRODALAM S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf142", rut: "94.050.000-1", nombre: "GENERAL MOTORS FINANCIAL CHILE S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf143", rut: "94.623.000-6", nombre: "SODEXO CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf144", rut: "94.625.000-7", nombre: "INVERSIONES ENEX S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf145", rut: "77.185.197-5", nombre: "RGPUBLICIDADSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf146", rut: "77.184.981-4", nombre: "ENDER JAIRO GARCIA ORTEGA, SERVICIOS DE FLETES Y TRASLADOS E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf147", rut: "95.000.000-7", nombre: "ISAPREE CIGNA SALUD", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf148", rut: "95.078.000-2", nombre: "ISAPRE NORMEDICA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf149", rut: "95.229.000-2", nombre: "FERRETERIA AMUNATEGUI SA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf150", rut: "96.355.000-6", nombre: "ELECTROCOM S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf151", rut: "96.501.450-0", nombre: "ING SALUD S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf152", rut: "96.501.500-0", nombre: "PLASTICOS DE INGENIERIA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf153", rut: "96.502.530-8", nombre: "ISAPRE VIDA TRES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf154", rut: "96.511.460-2", nombre: "CONSTRUMART S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf155", rut: "77.175.248-9", nombre: "TRANSFERFULLVANSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf156", rut: "77.171.330-0", nombre: "SOC GASTRONOMICA LAS VACAS GORDAS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf157", rut: "96.542.490-3", nombre: "TRECK S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf158", rut: "96.562.640-9", nombre: "COMERCIALIZADORA Y DISTRIBUIDORA VIVANCO S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf159", rut: "96.571.840-0", nombre: "ISAPRE VIDA PLENA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf160", rut: "96.572.800-7", nombre: "ISAPRE BANMEDICA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf161", rut: "96.645.500-4", nombre: "ISAPRE SFERA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf162", rut: "96.653.100-2", nombre: "REVESTIMIENTOS TÉCNICOS LTDA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf163", rut: "96.667.560-8", nombre: "TANNER SERVICIOS FINANCIEROS S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf164", rut: "96.695.020-K", nombre: "AMERPLAST SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf165", rut: "77.160.818-3", nombre: "INDUSTRIAL COMERCIAL CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf166", rut: "96.756.170-3", nombre: "CHRISTENSEN COMERCIAL S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf167", rut: "96.756.430-3", nombre: "CHILEXPRESS S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf168", rut: "96.785.470-0", nombre: "ISAPRE LA ARAUCANA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf169", rut: "96.792.430-K", nombre: "SODIMAC S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf170", rut: "96.803.460-K", nombre: "SHERWIN WILLIAMS CHILE S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf171", rut: "96.803.690-4", nombre: "EMPRESAS DMG SOCIEDAD ANONIMA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf172", rut: "96.806.110-0", nombre: "DARTEL S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf173", rut: "96.819.390-2", nombre: "PRINTEC S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf174", rut: "77.160.050-6", nombre: "AGRICOLA Y COMERC EL PALOMAR SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf175", rut: "77.146.631-1", nombre: "PUNTO FERRETERO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf176", rut: "96.881.530-K", nombre: "COMERCIAL DE VALORES ADMINISTRADORA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf177", rut: "96.904.280-0", nombre: "VIPAL CHILE SOCIEDAD ANONIMA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf178", rut: "96.907.830-9", nombre: "DESPEGAR.COM CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf179", rut: "96.919.050-8", nombre: "ACEPTA COM S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf180", rut: "96.921.060-6", nombre: "SOC COMERCIAL SANCHEZ HERRERA S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf181", rut: "77.146.615-K", nombre: "TODOASEOLAMPASPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf182", rut: "77.145.605-7", nombre: "COMERCIALIZADORA MI REFUGIO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf183", rut: "77.138.593-1", nombre: "D&A INVERSIONES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf184", rut: "97.004.000-5", nombre: "BANCO DE CHILE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf185", rut: "97.018.000-1", nombre: "SCOTIABANK CHILE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf186", rut: "97.023.000-9", nombre: "ITAU CORPBANCA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf187", rut: "97.036.000-K", nombre: "BANCO SANTANDER CHILE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf188", rut: "77.137.860-9", nombre: "COMERCIAL K LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf189", rut: "77.133.717-1", nombre: "COMERCIALIZADORA DOREMI SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf190", rut: "98.000.100-8", nombre: "AFP HABITAT S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf191", rut: "98.000.400-7", nombre: "AFP PROVIDA S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf192", rut: "98.000.600-K", nombre: "AFP SUMABANSANDER", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf193", rut: "98.000.900-9", nombre: "AFP PLANVITAL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf194", rut: "98.001.200-K", nombre: "AFP MAGISTER", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf195", rut: "99.528.050-7", nombre: "WEG CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf196", rut: "99.554.560-8", nombre: "COMERCIAL CCU SA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf197", rut: "99.578.050-K", nombre: "SHAW ALMEX CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf198", rut: "77.130.263-7", nombre: "CONSTRUCCIONESAITORSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf199", rut: "77.112.827-0", nombre: "ONE GEOTECNIA SUR SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf200", rut: "77.110.084-8", nombre: "FOXTROT INNOVACIONES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf201", rut: "77.104.280-5", nombre: "DISTRIB Y MONTAJE DE PROD INDUST DIPROIN LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf202", rut: "77.103.614-7", nombre: "COMERCIAL CHILEAIRES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf203", rut: "77.099.474-8", nombre: "ACEROSRMSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf204", rut: "77.096.019-3", nombre: "COMBUSTIBLES LO PINTO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf205", rut: "77.090.029-8", nombre: "SERVICIOS INTEGRALES MARIA ANDREA MEZA VILLARROEL E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf206", rut: "77.088.960-K", nombre: "COMERCIALIZADORA PIZARRO Y PIZARRO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf207", rut: "77.086.581-6", nombre: "ENTRETENIMIENTOS OOPS KIDS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf208", rut: "77.079.343-2", nombre: "MAESTRANZA L&T SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf209", rut: "77.077.609-0", nombre: "SAN ANTONIO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf210", rut: "77.077.092-0", nombre: "SAUTERBIMSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf211", rut: "77.073.851-2", nombre: "STARLINK CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf212", rut: "77.070.327-1", nombre: "VAN BEEK SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf213", rut: "77.068.352-1", nombre: "AUTOVIDRIOSROBIN SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf214", rut: "77.067.364-K", nombre: "CONSTRUCCIONES LC LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf215", rut: "77.067.279-1", nombre: "MACOVAL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf216", rut: "77.057.522-2", nombre: "FABRICA DE PRODUCTOS DE CAUCHO Y MAESTRANZA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf217", rut: "77.026.232-1", nombre: "IMPORTADORA Y EXPORTADORA XING LI LAI COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf218", rut: "77.018.016-3", nombre: "CONCEPTO CASAS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf219", rut: "77.015.124-4", nombre: "GRUPO PLUSVIDA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf220", rut: "77.008.658-2", nombre: "TORPEDO MENSAJEROS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf221", rut: "77.003.651-8", nombre: "CESAR AUGUSTO REYES FLORES, MECANICA INTEGRAL E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf222", rut: "76031005-0", nombre: "INVERSIONES Y ASESORIAS V&M LIMITADA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf223", rut: "76.996.279-4", nombre: "GEOCAMPOSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf224", rut: "76.993.859-1", nombre: "IKSO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf225", rut: "76.991.307-6", nombre: "DEFENSORIAS CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf226", rut: "76.985.912-8", nombre: "TU OFICINA VIRTUAL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf227", rut: "76.982.587-8", nombre: "DEMOLICIONESFRITZSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf228", rut: "76.975.504-7", nombre: "MURABLAST SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf229", rut: "76.974.611-0", nombre: "CISTERNA CONSTRUCCIÓN SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf230", rut: "76.967.600-7", nombre: "DISTRIBUIDORA DE PRODUCTOS PARA EL EMPAQUE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf231", rut: "76.960.424-3", nombre: "AFP UNO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf232", rut: "76.957.688-6", nombre: "METALDOOR LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf233", rut: "76.921.771-1", nombre: "GRUPO REACHEM CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf234", rut: "76.916.941-5", nombre: "TOC-TOCK NICOLAS IGNACIO CONCHA CORTES E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf235", rut: "76.916.167-8", nombre: "INGENIERIA E INVERSIONES PROMINCO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf236", rut: "76.916.147-3", nombre: "SERGIO SALAZAR CONTALBA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf237", rut: "76.914.453-6", nombre: "ASESORIAS MORALES & SANDOVAL LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf238", rut: "76.912.638-4", nombre: "TORNERIA RIOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf239", rut: "76.907.650-6", nombre: "COMERCIAL Y RESTAURANTE TRES MONTES LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf240", rut: "76.901.790-9", nombre: "FERRETERIA SASIL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf241", rut: "76.895.798-3", nombre: "METAL?RGICA ATOMET SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf242", rut: "76.894.110-6", nombre: "PRONTO INMOB SA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf243", rut: "76.885.372-K", nombre: "DEFENSA EMPRESARIAL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf244", rut: "76.877.825-6", nombre: "COMERCIALIZADORA VEMACO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf245", rut: "76.869.477-K", nombre: "FERRETERIA Y VIDRIERIA MAURICIO JEREZ ALVAREZ E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf246", rut: "76.862.977-3", nombre: "FR CONSTRUCCIONES INTERIORES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf247", rut: "76.859.034-6", nombre: "SOCIEDADGASTRONOMICAZHENXINGPANE.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf248", rut: "76.851.066-0", nombre: "TRANSPORTES Y MAQUINARIAS DOCAL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf249", rut: "76.848.930-0", nombre: "COMERCIAL CAVILUM LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf250", rut: "76.844.349-1", nombre: "COMAR SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf251", rut: "76.843.137-K", nombre: "COMERCIAL MISE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf252", rut: "76.833.720-9", nombre: "ABARROTES ECONOMICOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf253", rut: "76.830.421-1", nombre: "INVERSIONES RIVERA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf254", rut: "76.829.999-4", nombre: "GASTRONOMICA Y BANQUETERA SAN IGNACIO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf255", rut: "76.823.145-1", nombre: "PROASES INGENIERIA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf256", rut: "76.821.540-5", nombre: "PILAR ADET E HIJOS LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf257", rut: "76.821.330-5", nombre: "IMPERIAL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf258", rut: "76.815.296-9", nombre: "RUGRO DEMOLICIONES LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf259", rut: "76.806.867-4", nombre: "JUAN PABLO CAPO Y CIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf260", rut: "76.806.789-9", nombre: "AGUA ALKALINA SONJA VALESKA ALTAMIRANO ROJAS E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf261", rut: "76.804.006-0", nombre: "COMERCIAL E INVERSIONES SAYEN SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf262", rut: "76.803.563-6", nombre: "INDUSTRIAL FIERROMASTER LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf263", rut: "76.802.978-4", nombre: "SOCIEDAD COMERCIAL FACTORYNET CHILE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf264", rut: "76.801.400-0", nombre: "EDETER QUIMICA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf265", rut: "76.800.617-2", nombre: "ST FERRETERIAS Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf266", rut: "76.797.159-1", nombre: "INVERSIONES ANDESMART SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf267", rut: "76.788.425-7", nombre: "COMERCIALIZADORA SV LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf268", rut: "76.771.632-K", nombre: "CART PAPER LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf269", rut: "76.770.943-9", nombre: "SISTEMAS ONLINE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf270", rut: "76.762.740-8", nombre: "SOCIEDAD COMERCIALIZADORA DE REPUESTOS S.A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf271", rut: "76.762.250-3", nombre: "AFP MODELO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf272", rut: "76.762.218-K", nombre: "CONSTRUCTORA DE PISCINAS CRISTIAN ACEVEDO EMPRESA INDIVIDUAL DE RESPONSABILIDAD", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf273", rut: "76.762.046-2", nombre: "INFORMACION COMERCIAL LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf274", rut: "76.759.576-K", nombre: "INGENIERIA Y TRANSPORTES HBE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf275", rut: "76.756.768-5", nombre: "SEGURIDAD INDUSTRIAL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf276", rut: "76.756.630-1", nombre: "COM VASQUEZ Y CIA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf277", rut: "76.752.001-8", nombre: "ALTE INDUSTRIAL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf278", rut: "76.744.415-K", nombre: "OREGON CHEM GROUP SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf279", rut: "76.743.439-1", nombre: "COMERCIALIZADORA E IMPORTADORA VALENZUELA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf280", rut: "76.735.480-0", nombre: "COMERCIAL SHENG LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf281", rut: "76.733.699-3", nombre: "COMERCIAL INARCON SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf282", rut: "76.730.966-K", nombre: "CATASO LOGÍSTICA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf283", rut: "76.724.549-1", nombre: "COMERCIALIZADORA Y DISTRIBUIDORA DE ARTICULOS ELECTRICOS CORSIL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf284", rut: "76.720.231-8", nombre: "COMERCIALIZADORA FIDEX SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf285", rut: "76.714.437-7", nombre: "COMERCIO GEORGI ZENCOVICH ALVARADO EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITAD", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf286", rut: "76.707.404-2", nombre: "INGENIERIA E INFORMATICA AMERICO OMAR PALMA NUÑEZ EMPRESA INDIVIDUAL DE RESPONSA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf287", rut: "76.695.698-K", nombre: "IMPORTADORA IGEMAQ SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf288", rut: "76.686.096-6", nombre: "MAXIMUS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf289", rut: "76.684.730-7", nombre: "SERVICIOS MIGUEL ALARCON GONZALEZ E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf290", rut: "76.682.722-5", nombre: "SOLUCIONES KAME SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf291", rut: "76.678.757-6", nombre: "JOMO GRUAS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf292", rut: "76.670.529-4", nombre: "LUIS GUSTAVO ROCHA CRUCES MANTENCION Y REPARACION DE SISTEMAS ELECTRICOS E.I.R.L", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf293", rut: "76.670.281-3", nombre: "OXIGENO METROPOLITANO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf294", rut: "76.665.021-K", nombre: "COMERCIAL E INDUSTRIAL UGCE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf295", rut: "76.662.847-8", nombre: "PINTA CASA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf296", rut: "76.600.160-2", nombre: "SUMINISTROS EN ACERO INOXIDABLE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf297", rut: "76.597.170-5", nombre: "VICTOR MORALES ACEVEDO IMPORTACIONES Y HERRAMIENTAS E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf298", rut: "76.590.974-0", nombre: "C-REMODELA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf299", rut: "76.587.248-0", nombre: "ESCOBAR Y MALDONADO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf300", rut: "76.585.755-4", nombre: "ACB CONSTRUCTOR LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf301", rut: "76.568.660-1", nombre: "EASY RETAIL S.A. .-", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf302", rut: "76.558.692-5", nombre: "HUGO FERNANDO ESCOBAR ESPINOZA CONTRATISTA EN PINTURAS EIRL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf303", rut: "76.555.975-8", nombre: "COMERCIAL VERSALLES LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf304", rut: "76.552.231-5", nombre: "IMPORTADORA FULL ALARMS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf305", rut: "76.549.686-1", nombre: "COMERCIALIZADORA PC CITY LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf306", rut: "76.546.643-1", nombre: "COMERCIAL JAQUE Y BELTRAN LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf307", rut: "76.545.465-4", nombre: "BRAC SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf308", rut: "76.541.806-2", nombre: "RECTA SERVICIOS INDUSTRIALES LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf309", rut: "76.537.780-3", nombre: "AMBIENTAL INGENIERIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf310", rut: "76.526.403-0", nombre: "SCS Furniture Store S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf311", rut: "76.515.079-5", nombre: "ASESORIAS E INSPECCIONES ASMESOL LTADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf312", rut: "76.509.741-K", nombre: "COMERCIALIZADORA Y DISTRIBUIDORA STRATFORD LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf313", rut: "76.502.532-K", nombre: "Venta y Distribución de Materiales de Construcción Tu Construyes Limitada", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf314", rut: "76.496.130-7", nombre: "Sociedad Concesionaria Costanera Norte S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf315", rut: "76.494.259-0", nombre: "ZEPA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf316", rut: "76.486.633-9", nombre: "PAULO ALBERTO FERREIRO DIAZ TRANSPORTE DE CARGA POR CARRETERA E.I.R.L", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf317", rut: "76.481.823-7", nombre: "SOCIEDAD FERRETERA MOISES PENALOZA E HIJOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf318", rut: "76.475.719-K", nombre: "GVA TRADING SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf319", rut: "76.470.069-4", nombre: "MM ESTRUCTURAS METALICAS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf320", rut: "76.468.424-9", nombre: "B2B WEB DISTRIBUICAO DE PRODUTOS CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf321", rut: "76.466.581-3", nombre: "ACEROS PROCESOS & INGENIERIA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf322", rut: "76.464.402-6", nombre: "HOLZWERK SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf323", rut: "76.464.121-3", nombre: "COMERCIAL B L COTILLON DIVERSION Y ACCESORIOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf324", rut: "76.457.708-6", nombre: "SOCIEDAD COMERCIALIZADORA ELECTROKEY LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf325", rut: "76.448.025-2", nombre: "CAUCHOS Y POLIMEROS INDUSTRIALES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf326", rut: "76.447.562-3", nombre: "CROSSAIR SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf327", rut: "76.441.668-6", nombre: "FAMILIA Y ASOCIADOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf328", rut: "76.437.055-4", nombre: "SOCIEDAD QUINTANA Y ARTIAGA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf329", rut: "76.430.104-8", nombre: "ACEROS Y SERVICIOS PROVI-METAL LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf330", rut: "76.421.497-8", nombre: "IMPORTADORA Y COMERCIALIZADORA SDOOR LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf331", rut: "76.420.374-7", nombre: "CHILESTEEL Y SERVICIOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf332", rut: "76.408.775-5", nombre: "SOCIEDAD COMERCIAL ASTUDILLO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf333", rut: "76.398.157-6", nombre: "RENTA DE EQUIPOS Y MAQUINARIAS PRONTOMAQ LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf334", rut: "76.393.083-1", nombre: "FERRETERIA F M LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf335", rut: "76.392.932-9", nombre: "GAETE Y ARANEDA ASOCIADOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf336", rut: "76.389.680-3", nombre: "FABRICA Y DISTRIBUIDORA ZCB LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf337", rut: "76.389.469-K", nombre: "DEFONTANA CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf338", rut: "76.387.300-5", nombre: "Comercial e Industrial Cimex Spa", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf339", rut: "76.385.064-1", nombre: "COMERCIALIZADORA MARCO ANDRÉS CASTILLO FUENTES E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf340", rut: "76.384.035-2", nombre: "EMPRESA DE SERVICIOS A & C LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf341", rut: "76.380.642-1", nombre: "COMERCIALIZADORA CHAAC LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf342", rut: "76.378.846-6", nombre: "TECNOQUIM SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf343", rut: "76.360.868-9", nombre: "KIOSCLUB AMERICAN SUPERMARKET SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf344", rut: "76.345.808-3", nombre: "Pernos San Martin", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf345", rut: "76.345.360-K", nombre: "COMERCIALIZADORA CONDELL LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf346", rut: "76.344.361-2", nombre: "SOCIEDAD COMERCIAL FUENTES OYARZÚN LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf347", rut: "76.340.350-5", nombre: "RODRIGO RAMIREZ COMERCIALIZADORA E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf348", rut: "76.339.051-9", nombre: "SOC COM Y DIST SANTOMAR LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf349", rut: "76.338.734-8", nombre: "IMPORTADORA Y EXPORTADORA LA NUEVA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf350", rut: "76.338.225-7", nombre: "SERVICIOS AUTOMOTRICES LUIS OSVALDO RIQUELME MENESES E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf351", rut: "76.333.151-2", nombre: "MASTOOLS CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf352", rut: "76.325.899-8", nombre: "COMERCIAL FAMET LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf353", rut: "76.317.740-8", nombre: "COMERCIAL JAMC SERVICIOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf354", rut: "76.303.596-4", nombre: "COMERCIALIZADORA DANILO RICARDO ZÚÑIGA OLAVARRÍA E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf355", rut: "76.284.020-0", nombre: "Impresores Integrales Limitada", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf356", rut: "76.283.577-0", nombre: "Comercial e Industrial Triple E Ltda.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf357", rut: "76.276.658-2", nombre: "COMERCIAL E INDUSTRIAL CLIMAREP LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf358", rut: "76.258.505-7", nombre: "GEMS NDT SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf359", rut: "76.257.901-4", nombre: "Operaciones Los Andes S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf360", rut: "76.256.513-7", nombre: "CUBIERTAS DE CHILE KUBIEC SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf361", rut: "76.255.044-K", nombre: "RENNER COATINGS CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf362", rut: "76.249.931-2", nombre: "Ferrocor", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf363", rut: "76.249.675-5", nombre: "REPUESTOS Y PARTES AUTOMOTRICES RODACAMP LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf364", rut: "76.247.147-7", nombre: "INVERSIONES Y ASESORIAS CENTRO MEDICO DEL TRABAJADOR SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf365", rut: "76.241.219-5", nombre: "ESTACION DE SERVICIOS DIPENA Y CIA LTDA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf366", rut: "76.237.450-1", nombre: "ABASTECEDORA ACEROS BARBATO E HIJO Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf367", rut: "76.235.519-1", nombre: "SERVICIOS INTEGRALES PARA AUTOMOVILES ARCH LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf368", rut: "76.231.696-K", nombre: "COMERCIAL FERNANDO BRAVO Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf369", rut: "76.231.469-K", nombre: "PLASTICINA ASESORIA PUBLICITARIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf370", rut: "76.229.100-2", nombre: "Importaciones y Exportaciones Industriales Nozzles SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf371", rut: "76.222.391-0", nombre: "TRANSPORTES CHRISAR EIRL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf372", rut: "76.218.711-6", nombre: "EXPENDIO DE COMBUSTIBLE Y MINIMARKET CARLOS ALBERTO HERRERA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf373", rut: "76.214.881-1", nombre: "MASCOTAMANIA CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf374", rut: "76.211.240-K", nombre: "KAUDAT SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf375", rut: "76.211.207-8", nombre: "SOLUCIONES QUIMICAS INTEGRALES COMERCIAL SA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf376", rut: "76.207.304-8", nombre: "GASTRONOMIA ESCAFANDRA LIMITADA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf377", rut: "76.203.900-1", nombre: "Sociedad Restaurant CasaBosque y Compañia Limitada", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf378", rut: "76.202.140-4", nombre: "Ceel Ingeniería Limitada", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf379", rut: "76.191.855-9", nombre: "INVERSIONES LLOZA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf380", rut: "76.184.324-9", nombre: "COMERCIAL CLICKDEAL CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf381", rut: "76.182.739-1", nombre: "PINTURAS TRICOLOR S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf382", rut: "76.180.092-2", nombre: "Transportes y Gruas Raimundo Lorenzo Lizama Perez EIRL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf383", rut: "76.178.360-2", nombre: "CENTRAL DE RESTAURANTES ARAMARK LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf384", rut: "76.173.410-5", nombre: "QWANTEC INGENIERÍA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf385", rut: "76.171.627-1", nombre: "DISTRIBUIDORA DE GAS RIGOBERTO ORELLANA EIRL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf386", rut: "76.170.269-6", nombre: "SOCIEDAD COMERCIAL MELINKA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf387", rut: "76.163.793-2", nombre: "PLASTICENTRO S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf388", rut: "76.159.920-8", nombre: "SERVICIO DE METROLOGIA INTEGRAL SpA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf389", rut: "76.147.293-3", nombre: "COMERCIALIZADORA PROSEC CHILE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf390", rut: "76.140.725-2", nombre: "Ayrsa", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf391", rut: "76.138.428-7", nombre: "IMPORTACIONES REUS S P A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf392", rut: "76.134.946-5", nombre: "ADMIN. DE SUPERMERCADOS EXPRESS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf393", rut: "76.134.941-4", nombre: "ADMIN. DE SUPERMERCADOS HIPER LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf394", rut: "76.134.794-2", nombre: "FABRICACION VISTALIBRE LTDA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf395", rut: "76.124.890-1", nombre: "Telefónica Móviles Chile S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf396", rut: "76.121.617-1", nombre: "SERGIO H. IGLESIAS JAÑA EIRL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf397", rut: "76.120.104-2", nombre: "INL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf398", rut: "76.116.780-4", nombre: "EGLO CHILE ILUMINACION LTDA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf399", rut: "76.113.666-6", nombre: "ABASTECEDORA DE VIDRIOS Y ALUMINIOS LARRAIN LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf400", rut: "76.105.493-7", nombre: "EBT S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf401", rut: "76.103.067-1", nombre: "RESTAURANT DEL CARAJO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf402", rut: "76.097.186-3", nombre: "GLADYS HORMAZABAL CALDERON EMPRESA EDUCACIONAL WESTON ACADEMY E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf403", rut: "76.094.369-K", nombre: "MANRIQUEZ ASOCIADOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf404", rut: "76.090.397-3", nombre: "FILIPPA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf405", rut: "76.087.785-9", nombre: "TRANSPORTES EMETRA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf406", rut: "76.086.346-7", nombre: "PROD DISENO INTEGRAL LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf407", rut: "76.085.400-K", nombre: "ELFLE COMERCIAL DOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf408", rut: "76.084.243-5", nombre: "CAPITAL EXPRESS SERVICIOS DE COBRANZA S.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf409", rut: "76.080.792-3", nombre: "CONSTRUCTORA DISENO Y PAISAJISMO RODIN LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf410", rut: "76.079.845-2", nombre: "HU LAI LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf411", rut: "76.077.800-1", nombre: "SOCIEDAD GRAFICA HASS COPY LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf412", rut: "76.073.802-6", nombre: "GASTRONOMICA LOS VIKINGOS S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf413", rut: "76.072.177-8", nombre: "BODEGA TAQUERAL LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf414", rut: "76.072.013-5", nombre: "TRANSPORTES GALAZ E HIJO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf415", rut: "76.070.083-5", nombre: "ACEROS BRAVO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf416", rut: "76.067.310-2", nombre: "MADIMEX MADERAS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf417", rut: "76.057.232-2", nombre: "UTOPIKO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf418", rut: "76.053.393-9", nombre: "SOCIEDAD COMERCIAL PANELES DEL MAULE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf419", rut: "76.053.044-1", nombre: "FERRETERIA ALEJANDRO VEAS", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf420", rut: "76.052.927-3", nombre: "Soc. Conc. Autopista Nueva Vespucio Sur S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf421", rut: "76.046.809-6", nombre: "DAP DUCASSE DISEÑO LTDA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf422", rut: "76.045.598-9", nombre: "SOCIEDAD COMERCIAL GRUPO YES CHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf423", rut: "76.037.465-2", nombre: "IMPORTADORA RIOS Y COMPAÑIA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf424", rut: "76.036.532-7", nombre: "CENTRO COMERCIAL CHINA TOWN LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf425", rut: "76.035.295-0", nombre: "Agricola, Ganadera y Comercial Punto Vip Ltda", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf426", rut: "76.025.032-5", nombre: "COMERCIAL FOB SPA.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf427", rut: "76.024.700-6", nombre: "Napoki & Trincado Ltda.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf428", rut: "76.023.606-3", nombre: "INVERSIONES D.M.G. S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf429", rut: "76.017.823-3", nombre: "FLEXIBLES HIDRAULICOS JOSE AGUSTIN NUNEZ REYES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf430", rut: "76.014.678-1", nombre: "MOVIMIENTOS DE TIERRA IVAN GONZALEZ OLIVEROS E.I.R.L.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf431", rut: "76.013.474-0", nombre: "MACAYA INSUMOS INDUSTRIALES LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf432", rut: "76.001.749-3", nombre: "PLAZMA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf433", rut: "70.360.100-6", nombre: "ACHS-ASOCIACION CHILENA DE SEGURIDAD", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf434", rut: "70.285.100-9", nombre: "MUTUAL DE SEGURIDAD DE LA C.CH.C.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf435", rut: "70.096.350-0", nombre: "CCAF GABRIELA MISTRAL", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf436", rut: "70.017.820-K", nombre: "CAMARA DE COMERCIO DE SANTIAGO A G", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf437", rut: "70.016.330-K", nombre: "CCAF LOS HEROES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf438", rut: "70.016.160-9", nombre: "CCAF LA ARAUCANA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf439", rut: "70.015.580-3", nombre: "ISP-INSTITUTO DE SEGURIDADA DEL TRABAJADOR", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf440", rut: "70.013.360-5", nombre: "CCAF JAVIERA CARRERA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf441", rut: "7.776.856-4", nombre: "MIGUEL CESAREO GONZALEZ PLAZA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf442", rut: "7.772.509-1", nombre: "PATRICIA ILONKA CSILLAG PIMSTEIN", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf443", rut: "7.278.107-4", nombre: "GILDA ELIZABETH MIRANDA CORDOVA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf444", rut: "7.192.075-5", nombre: "JOSE LUIS VERA ALVAREZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf445", rut: "7.128.013-6", nombre: "SERGIO FUENTES CANALES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf446", rut: "6925762-3", nombre: "MANUEL RAUL BRAVO ACEVEDO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf447", rut: "65.815.260-2", nombre: "COMITE FONDAS Y RAMADAS DE LA PROVINCIA CORDILLERA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf448", rut: "61.603.000-0", nombre: "FONASA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf449", rut: "61.533.000-0", nombre: "INP", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf450", rut: "6.740.607-9", nombre: "JUAN ANTONIO BRUNA FERNANDEZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf451", rut: "6.505.405-1", nombre: "JUAN BELISARIO ABARCA CASTRO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf452", rut: "6.444.093-4", nombre: "MARIA ERNESTINA SARABIA VALLE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf453", rut: "6.415.976-3", nombre: "HECTOR WASHINGTON SANCHEZ MORALES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf454", rut: "6.280.637-0", nombre: "LUIS ALFONSO MOYA SCOTT", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf455", rut: "6.203.950-7", nombre: "ENRIQUE RAMIREZ ASTUDILLO VENTAS@HURACANES.CL FONO 25526727 - 25527820", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf456", rut: "6.054.563-4", nombre: "DANIEL EDGARDO RODRIGUEZ SALINAS", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf457", rut: "5.890.147-4", nombre: "EDUARDO CRISTHIAN FERRI MASCIO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf458", rut: "5.869.464-9", nombre: "LUIS ANATOLIO GAJARDO NUNEZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf459", rut: "5.404.296-5", nombre: "JAIME DEL CARMEN ROJO MONTENEGRO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf460", rut: "5.248.764-1", nombre: "RAMON HERNAN MENESES VALENZUELA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf461", rut: "4.666.641-0", nombre: "ISABEL ESTERBINA MALTES JARAMILLO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf462", rut: "4.343.943-K", nombre: "SEGUNDO GERMAN DONOSO MACIAS", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf463", rut: "26766506-0", nombre: "ALIRIO JOSE", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf464", rut: "26.670.448-8", nombre: "JHON FREDDY GONZALEZ GRAJALES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf465", rut: "22697182-3", nombre: "DARWING EDUARDO GONZALEZ RUIZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf466", rut: "20329965-6", nombre: "THOMAS ABRAHAM DONOSO RAMOS", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf467", rut: "19.740.630-5", nombre: "LEFTRARO RAFAEL TIRADO GONZALEZ", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf468", rut: "18243465-5", nombre: "EDUARDO JAVIER DUARTE MALDONAD", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf469", rut: "18.863.011-1", nombre: "GABRIEL ANTONIO DE LA QUINTANA OSORIO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf470", rut: "17780433-9", nombre: "PABLO VALENTINO ARAYA CALDERON", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf471", rut: "17334694-8", nombre: "JUAN PABLO ZUNIGA AMPUERO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf472", rut: "17.486.060-2", nombre: "CARLOS ALEJANDRO AHUMADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf473", rut: "17.230.620-9", nombre: "KARINA SOLEDAD CATALDO KUSMA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf474", rut: "77.860.539-2", nombre: "INVERSIONES NTLP SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf475", rut: "77.859.490-0", nombre: "NOVOPLAST SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf476", rut: "77.857.360-1", nombre: "RUEDLINGER Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf477", rut: "77.837.139-1", nombre: "MAESTRANZA OLIMPO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf478", rut: "77.836.714-9", nombre: "SOCIEDAD DE SERVICIOS INTEGRALES DE ANDAMIOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf479", rut: "77.829.225-4", nombre: "INVERSIONES SUYAI SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf480", rut: "77.817.768-4", nombre: "TODO DIVERSION SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf481", rut: "77.812.490-4", nombre: "CERAMICAS ALVARADO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf482", rut: "77.811.058-K", nombre: "RESTOBAR TINKU SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf483", rut: "77.810.015-0", nombre: "REY BRAVO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf484", rut: "77.796.602-2", nombre: "INVERSIONESYPROYECTOSSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf485", rut: "77.790.541-4", nombre: "HNDZ TRANSPORTES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf486", rut: "77.782.658-1", nombre: "RC COMBUSTIBLES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf487", rut: "77.780.569-K", nombre: "SERVI-AGROSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf488", rut: "77.777.914-1", nombre: "OXICORTE Y TRANSPORTE R Y L SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf489", rut: "77.774.047-4", nombre: "TRANPORTESLUX SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf490", rut: "77.773.356-7", nombre: "EMPRESA DE TRANSPORTE NARENDRA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf491", rut: "77.769.192-9", nombre: "DEFONTANAFINTECHSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf492", rut: "77.765.308-3", nombre: "FERRETERIA LO PINTO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf493", rut: "77.753.400-9", nombre: "IMPORTADORA Y EXPORTADORA EVALC LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf494", rut: "77.749.063-K", nombre: "FERRE MACHINE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf495", rut: "77.733.302-K", nombre: "EMPORIO LO PINTO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf496", rut: "77.727.458-9", nombre: "IMPORTADORA NANMAO CHILE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf497", rut: "77.725.100-7", nombre: "CERMAT LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf498", rut: "77.709.865-9", nombre: "DVA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf499", rut: "77.708.540-9", nombre: "IMPORTADORA DOWNLIGHT SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf500", rut: "77.703.752-8", nombre: "COMERCIALIZADORA CASTIGROUP SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf501", rut: "77.669.563-7", nombre: "ADMINISTRADORA BARBACOA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf502", rut: "77.660.960-9", nombre: "ACENOR ACEROS DEL NORTE SA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf503", rut: "77.653.093-K", nombre: "PUYEHUESOLUCIONESSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf504", rut: "77.638.689-8", nombre: "INVERSIONESDONAPICHASPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf505", rut: "77.626.362-1", nombre: "DISTRIBUIDORA Y COMERCIALIZADORA RODRIGO RUIZ SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf506", rut: "77.616.334-1", nombre: "TRANSPORTES ISIZA JIMÉNEZ SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf507", rut: "77.615.158-0", nombre: "EL CAMINO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf508", rut: "77.609.235-5", nombre: "MADERAS LOS MORROS LAMPA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf509", rut: "77.602.970-K", nombre: "INSUMOS Y SERVICIOS INDUSTRIALES MAGEVA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf510", rut: "77.598.630-1", nombre: "ADASME Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf511", rut: "77.582.588-k", nombre: "PRODUFI SERVICE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf512", rut: "77.580.620-6", nombre: "IMPORT Y DISTRIB DE FLORES CLARA MORAGA E HIJOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf513", rut: "77.577.655-2", nombre: "DÍAZ ÁLVAREZ HERMANOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf514", rut: "77.567.357-5", nombre: "METROLOGÍA Y CALIDAD SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf515", rut: "77.561.202-9", nombre: "CORPORACION L&P SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf516", rut: "77.558.098-4", nombre: "TRANSPORTESYMAQUINARIASALFADISPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf517", rut: "77.558.097-6", nombre: "INGENIERIA Y CONSTRUCCION DAF SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf518", rut: "77.557.756-8", nombre: "SMART SECURITY SYS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf519", rut: "77.555.278-6", nombre: "AVATAR MARKETING LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf520", rut: "77.543.731-6", nombre: "CREAVISION MEDIA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf521", rut: "77.539.206-1", nombre: "SOCIEDAD GASTRONÓMICA DEL MAIPO SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf522", rut: "77.534.433-4", nombre: "COMERCIALIZADORA DE PRODUCTOS DEL MAR Y OTROS AJV SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf523", rut: "77.519.707-2", nombre: "ACTIVIDADES DE RESTAURANTES Y DE SERVICIO MÓVIL DE COMIDAS, CRISTIAN R", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf524", rut: "77.505.101-9", nombre: "FERRETERIA VERSALLES SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf525", rut: "77.493.544-4", nombre: "COMERCIALIZADORA E IMPORTADORA MAGNOLOGY SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf526", rut: "77.485.574-2", nombre: "DIARLIT ARMADURAS ANTIRROBOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf527", rut: "77.485.292-1", nombre: "JARDINES DE LAMPA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf528", rut: "77.481.676-3", nombre: "SERVICIOSRYMSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf529", rut: "77.472.925-9", nombre: "ALIVIO DEUDORES", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf530", rut: "77.458.590-7", nombre: "SOC DISTRIBUIDORA DE PERNOS INDEPENDENCIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf531", rut: "77.454.587-5", nombre: "SANCHEZ HERMANOS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf532", rut: "77.451.570-4", nombre: "NORIEGA MATERIALES DE CONSTRUCCION LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf533", rut: "77.451.397-3", nombre: "SOLUCIONESPARACONSTRUCCIÓNEINDUSTRIASPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf534", rut: "77.450.131-2", nombre: "METALMECANICA TAY SpA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf535", rut: "77.437.026-9", nombre: "DISTRIBUIDORA DE COMBUSTIBLES JJS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf536", rut: "77.435.230-9", nombre: "NEUMATICOS Y LLANTAS DEL PACIFICO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf537", rut: "77.434.393-8", nombre: "INVERSIONESDISASPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf538", rut: "77.423.125-0", nombre: "E-DIGITAL PKI SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf539", rut: "77.414.534-6", nombre: "QUIMICA ANDINA CHILE S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf540", rut: "77.412.320-2", nombre: "IMPORTADORA Y DISTRIBUIDORA ULTRA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf541", rut: "77.398.220-1", nombre: "MERCADOLIBRE CHILE LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf542", rut: "77.393.874-1", nombre: "INMOBILIARIA E INVERSIONES PUERTO TRANQUILO LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf543", rut: "77.391.310-2", nombre: "COMERCIAL Y GASTRONOMICA INTERNACIONAL S.P.A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf544", rut: "77.384.394-5", nombre: "ISTRIAMAQUINASYHERRAMIENTASLIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf545", rut: "77.375.966-9", nombre: "TU OFICINA VIRTUAL SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf546", rut: "77.362.766-5", nombre: "COMERCIALIZADORA DE MATERIALES DE CONSTRUCCIÓN EDUARDO ROSENDO RAILAF", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf547", rut: "77.360.898-9", nombre: "GRUPO CG SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf548", rut: "77.355.422-6", nombre: "ALVARADO E HIJOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf549", rut: "77.351.814-9", nombre: "IMPORTADORAFULLMUEBLESSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf550", rut: "77.349.302-2", nombre: "TRANSPORTES HRF SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf551", rut: "77.343.839-0", nombre: "CONSTRUFERRE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf552", rut: "77.342.392-K", nombre: "CONSTRUCTORA Y COMERCIALIZADORA FERROMAS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf553", rut: "77.341.032-1", nombre: "NDT SOLUTIONS SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf554", rut: "77.327.430-4", nombre: "ADMINISTRADORA DE TURISMO ROSA AGUSTINA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf555", rut: "77.316.733-8", nombre: "SERVICIOS DE INGENIERÍA MARCOS ANDRES SALDIAS SAGREDO EMPRESA INDIVIDU", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf556", rut: "77.926.233-2", nombre: "GALAZ INGENIERIA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf557", rut: "78.002.942-0", nombre: "COMERCIAL FMTEX SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf558", rut: "78.012.550-0", nombre: "PERNOSTOCK LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf559", rut: "78.013.031-8", nombre: "OUTLET AURORA A&T SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf560", rut: "78.060.562-6", nombre: "COMBUSTIBLES LAMPA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf561", rut: "78.076.334-5", nombre: "SEGURYFER SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf562", rut: "78.076.361-2", nombre: "CASA ALTUM SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf563", rut: "78.127.467-4", nombre: "Ferretería y Certificación de Instrumentos Industriales Spa", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf564", rut: "78.131.690-3", nombre: "SOC COMERCIAL CRUZEIRO GOMAS LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf565", rut: "78.179.732-4", nombre: "IMPORTACIONESTAMYSPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf566", rut: "78.218.269-2", nombre: "GRUPO ZENTRA INGENIERÍA ELÉCTRICA SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf567", rut: "78.529.170-0", nombre: "SOC COMERCIAL E INDUSTRIAL PROEXI LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf568", rut: "79.615.510-8", nombre: "EMILIO POHL Y COMPANIA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf569", rut: "79.903.920-6", nombre: "COMERCIAL HISPANO CHILENA LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf570", rut: "80.478.200-1", nombre: "ILOP S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf571", rut: "80.565.900-9", nombre: "YOLITO BALART HERMANOS LIMITADA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf572", rut: "81.151.200-1", nombre: "AMSTER S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf573", rut: "81.461.700-9", nombre: "ISAPRE PROMEPART", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf574", rut: "81.533.000-5", nombre: "DANILO JORDAN S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf575", rut: "83.574.800-6", nombre: "PATRICIO LIOI Y CIA LTDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf576", rut: "86.708.800-8", nombre: "BADAMAX RETAIL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf577", rut: "89.441.300-K", nombre: "ISAPRE RIO BLANCO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf578", rut: "89.563.800-5", nombre: "IMPORTADORA INDUSTRIAL MOLYCHILE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf579", rut: "89.689.900-7", nombre: "DE VICENTE PLASTICOS S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf580", rut: "9.083.892-K", nombre: "CARMEN LUZ MONTECINOS MATUS DE LA PARRA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf581", rut: "9.090.599-6", nombre: "JORGEANTONIOMORALESPONCEDELEON", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf582", rut: "9.151.396-K", nombre: "JUAN FERNANDO VALENZUELA TORO", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf583", rut: "92.617.000-7", nombre: "INGOMAR S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf584", rut: "92.642.000-3", nombre: "ARTEL S A I C", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf585", rut: "94.668.000-1", nombre: "CODELPA CHILE S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf586", rut: "94.954.000-6", nombre: "ISAPRE COLMENA GOLDEN CROSS", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf587", rut: "96.522.500-5", nombre: "ISAPRE MASVIDA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf588", rut: "96.539.970-4", nombre: "PERNOVAL S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf589", rut: "96.702.950-5", nombre: "FERRETERIA GARACHENA S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf590", rut: "96.856.780-2", nombre: "ISAPRE CONSALUD", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf591", rut: "96.871.890-8", nombre: "COMERCIAL TOP LINE SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf592", rut: "96.928.180-5", nombre: "EMPRESA NACIONAL DE CERTIFICACION ELECTRONICA S A", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf593", rut: "96.938.840-5", nombre: "BLUE EXPRESS S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf594", rut: "96.941.720-0", nombre: "IC CORP SPA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf595", rut: "98.000.000-1", nombre: "AFP SANTA MARIA", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf596", rut: "98.000.000-7", nombre: "AFP CUPRUM", giro: "", direccion: "", comuna: "", estado: "Activo" },
  { id: "pf597", rut: "99.580.240-6", nombre: "ACF CAPITAL S.A.", giro: "", direccion: "", comuna: "", estado: "Activo" },
]
